### ISSUE TITLE
Can't look up JM's local orderbook

### ISSUE THREAD

**Issue by raindogdance** [kristapsk/raspibolt-extras#10]
I am trying to look up JM orderbook locally on my Raspibolt, following the steps as described here: https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/orderbook.md  

I am getting the following output: 

```
python ob-watcher.py
2020-12-06 18:09:00,943 [WARNING]  matplotlib not found, charts will not be available. Do `pip install matplotlib` in the joinmarket virtualenv.

2020-12-06 18:09:02,568 [INFO]  Starting ob-watcher
2020-12-06 18:09:07,672 [INFO]  joined: #joinmarket-pit irc-eu-1.darkscience.net
2020-12-06 18:09:07,677 [INFO]  Could not connect to *ALL* servers yet, waiting up to 60 more seconds.
2020-12-06 18:09:08,672 [INFO]  joined: #joinmarket-pit guybrush.hackint.org
2020-12-06 18:09:08,675 [INFO]  All IRC servers connected, starting execution.

started http server, visit http://localhost:62601/
```

On my laptop, I tried to copypaste the link above into my browser, as well as trying my Raspibolt's local IP `http://[192.168.xxx]:62601/`, but getting the error "cannot connect to server" in both cases. 

Is there anything I can do to see the orderbook on the Raspibolt?

**Comment by openoms** [comment]
Allow it through the firewall:
`sudo ufw allow 62601`

**Comment by raindogdance** [comment]
Thanks, added the ufw rule, so now it says: `62601 (v6)                 ALLOW       Anywhere (v6)              # allow Joinmarket orderbook`, but this didn't seem to help (also tried restarting ufw and then the whole node). Still same error (tried with different browsers too).

**Comment by openoms** [comment]
I only use it as a Tor Hidden Service see how to setup: https://github.com/openoms/bitcoin-tutorials/blob/master/tor_hidden_service_example.md

**Comment by raindogdance** [comment]
I tried the guide, thx. I'm not sure if I'm entering the onion address right (in the last step for looking up the orderbook).  

So my steps in detail:  
- stopped bitcoind
- followed your Tor guide
- noted my onion address under `sudo cat /var/lib/tor/thunderhub/hostname`
- restarted bitcoind
- launched `python ob-watcher.py` 
- tried to connect over Tor browser by simply entering the whole onion address into the browser (with the result "browser can’t establish a connection to the server at [myaddress].onion")

Do I need to specify anything in particular when entering the address?

**Comment by openoms** [comment]
Sorry if it was was not self-explanatory. The guide is an example using Thunderhub. You need to change the port 3010 to the port the ob-watcher is using and maybe call it ob-watcher rather then thunderhub.

also there is no need to stop bitcoind.

**Comment by raindogdance** [comment]
Oh it worked now! Awesome :) Thank you sir!  

Side question: Is there any (privacy) risk involved in keeping it running like that, anything I should keep in mind?

**Comment by openoms** [comment]
It is just an isolated hidden service showing publicly available info with the IPaddress hidden by Tor so I don't see any issues.

Maybe a DOS attack if you publish the address to widely, but can always change it by deleting the privkey of the address from the directory where the hostname is.

**Comment by raindogdance** [comment]
Great, good to know.  

Appreciate your help, thanks again :)  

Closing the issue now.

**Comment by kristapsk** [comment]
ob-watcher by default binds only to localhost, not LAN interface, that's why it works only locally or using Tor onion service at that is just a proxy to localhost. Use -H/--host parameter if you want orderbook to be accessible from LAN.
```
  -H HOST, --host=HOST  hostname or IP to bind to, default=localhost
```
