### ISSUE TITLE
How to recreate the default joinmarket.cfg?

### ISSUE THREAD

**Issue by raindogdance** [kristapsk/raspibolt-extras#11]
Hi,  

I am running the newest Joinmarket release (0.9.3). Noticed that my joinmarket.cfg file hasn't been updating for a while, f.ex I can't find the yieldgenerator fee settings which I used to adjust by opening `nano yg-privacyenhanced.py ` but those have since then moved to the config file, according to 0.8.1 [release notes](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/8c57852b2ae3c5a6ca0ec39724495d391982cfc2/docs/release-notes/release-notes-0.8.1.md). My config file seems to be from the time before that release.  

The link above also suggests to back up and recreate the config file. What is the way to go about that? Alternatively, could someone please post the up-to-date default config? I think I found it [here](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/59f5da5eed1ddfbfdef3c13a24620c6ef16b69ce/jmclient/jmclient/configure.py#L91) (from line 91) but not entirely sure if that's the right one. If it is, I guess I can simply copy paste it into my joinmarket.cfg file (and adjust the necessary lines)?

Thanks :)

**Comment by kristapsk** [comment]
Currently fastest way will be to backup and then delete existing `~/.joinmarket/joinmarket.cfg`. On the next run any JM tools will create new config file with default values which user then needs to edit.

> I think I found it here (from line 91)

Yes, that's the code used to create default config file if it's missing and to have defaults for values that are not specified in your config file. Alternative to method above is to manually look at what new settings you may be interested in are added.

**Comment by raindogdance** [comment]
> Currently fastest way will be to backup and then delete existing ~/.joinmarket/joinmarket.cfg. On the next run any JM tools will create new config file with default values which user then needs to edit.  

Ah thx, done that, all works.  

In the new config file there are configs for '[MESSAGING:server3]', which in my old config file were commented out with the note '#Agora sometimes seems to be unreliable. Not active by default for that reason.'. The Raspibolt guide doesn't mention what to do with it. Since I run on Tor, I didn't want to risk any clearnet connections and simply uncommented that whole area (as I had before in the old config). Any disadvantages with that, or should I configure it to connect over Tor as well?  

Thanks once again :)

**Comment by kristapsk** [comment]
Agora was re-enabled by default about month ago, see https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1026.

Definitely use only Tor connection (vxecvd6lc4giwtasjhgbrr3eop6pzq6i5rveracktioneunalgqlwfad.onion) or keep it disabled.

**Comment by raindogdance** [comment]
Would those setting be correct then (not sure if `usessl` and `port` should be uncommented or not)?  

[MESSAGING:server3]
#host = agora.anarplex.net
channel = joinmarket-pit
port = 14716
usessl = true
#socks5 = false
socks5_host = localhost
socks5_port = 9050

#for tor
host = vxecvd6lc4giwtasjhgbrr3eop6pzq6i5rveracktioneunalgqlwfad.onion
port = 6667
usessl = false
socks5 = true

**Comment by kristapsk** [comment]
You should also comment out `port = 14716` and `usessl = true`. But I also updated the doc a moment ago, look at the current master.

**Comment by raindogdance** [comment]
Yep, many thanks, all updated :)  

closing now
