### ISSUE TITLE
Error encountered trying to initialize a JM wallet on v3 Raspibolt

### ISSUE THREAD

**Issue by pleb4868** [kristapsk/raspibolt-extras#14]
I have set up a new pi using the raspibolt v3 guide.

I am encountering the following error:

<pre>(jmvenv) <font color="#4E9A06"><b>bitcoin@raspibolt</b></font>:<font color="#3465A4"><b>~/joinmarket/scripts $</b></font> python wallet-tool.py WalletFSN.jmdat
<font color="#3465A4"><b>User data location: /home/bitcoin/.joinmarket/</b></font>
Enter passphrase to decrypt wallet: 
Traceback (most recent call last):
  File &quot;/home/bitcoin/joinmarket-clientserver-0.9.6/scripts/wallet-tool.py&quot;, line 6, in &lt;module&gt;
    jmprint(wallet_tool_main(&quot;wallets&quot;), &quot;success&quot;)
  File &quot;/home/bitcoin/joinmarket-clientserver-0.9.6/jmclient/jmclient/wallet_utils.py&quot;, line 1586, in wallet_tool_main
    if wallet_service.sync_wallet(fast = not options.recoversync):
  File &quot;/home/bitcoin/joinmarket-clientserver-0.9.6/jmclient/jmclient/wallet_service.py&quot;, line 490, in sync_wallet
    self.sync_wallet_fast()
  File &quot;/home/bitcoin/joinmarket-clientserver-0.9.6/jmclient/jmclient/wallet_service.py&quot;, line 518, in sync_wallet_fast
    self.sync_addresses_fast()
  File &quot;/home/bitcoin/joinmarket-clientserver-0.9.6/jmclient/jmclient/wallet_service.py&quot;, line 556, in sync_addresses_fast
    self.get_address_usages()
  File &quot;/home/bitcoin/joinmarket-clientserver-0.9.6/jmclient/jmclient/wallet_service.py&quot;, line 534, in get_address_usages
    agd = self.bci.listaddressgroupings()
  File &quot;/home/bitcoin/joinmarket-clientserver-0.9.6/jmclient/jmclient/blockchaininterface.py&quot;, line 575, in listaddressgroupings
    return self._rpc(&apos;listaddressgroupings&apos;, [])
  File &quot;/home/bitcoin/joinmarket-clientserver-0.9.6/jmclient/jmclient/blockchaininterface.py&quot;, line 234, in _rpc
    res = self.jsonRpc.call(method, args)
  File &quot;/home/bitcoin/joinmarket-clientserver-0.9.6/jmclient/jmclient/jsonrpc.py&quot;, line 165, in call
    raise JsonRpcError(response[&quot;error&quot;])
jmclient.jsonrpc.JsonRpcError: {&apos;code&apos;: -18, &apos;message&apos;: &apos;No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)&apos;}
</pre>

I installed the latest Jm (0.9.6) and my joinmarket external library is at /data/joinmarket

Would appreciate your help

**Comment by kristapsk** [comment]
Yes, this guide needs update.

Old Bitcoin Core versions created default wallet in Core, which JM uses for watching incoming transactions (it's watch-only wallet, private keys aren't there, they are only in encrypted JM wallet file). See instructions here - https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/USAGE.md#setting-core-wallet.

**Comment by pleb4868** [comment]
It worked, thank you!
