### ISSUE TITLE
repeatedly getting the error "Commitment is blacklisted"

### ISSUE THREAD

**Issue by raindogdance** [kristapsk/raspibolt-extras#16]
Hi, I'm running the yieldgenerator (JM 0.9.9) and since a few days it repeatedly and very frequently (like, every hour or two) throws the error in the title. So the last lines in my current log file look like this (edited out the error strings, which all start with J5, and the actual commitment strings, as I have no idea if it might be bad for privacy):  

`2023-03-07 16:41:14,866 [INFO]  error<[edit]> : Commitment is blacklisted: [long string]`  
`2023-03-07 16:45:21,835 [INFO]  error<[edit]> : Commitment is blacklisted: [long string]`
`2023-03-07 16:52:12,095 [INFO]  error<[edit]> : Commitment is blacklisted: [long string]`
`2023-03-07 17:05:27,915 [INFO]  error<[edit]> : Commitment is blacklisted: [long string]`
`2023-03-07 18:19:26,928 [INFO]  error<[edit]> : Commitment is blacklisted: [long string]`

Searching through docs and issues on the JM Github for that error message doesn't get much. Is it something I should be worrying about, and how would I go about finding the source of the error?  

Have been running the yieldgenerator for a while now without issues, the error started appearing without me changing anything, IIRC (I updated a few weeks ago from 0.9.8 to 0.9.9 but it has been running and doing coinjoins without the error up until the last few days - although I think it still is doing coinjoins anyway).

**Comment by kristapsk** [comment]
It's ok, when taker doesn't proceed with all stages of coinjoin, their PoDLE commitment gets blacklisted (after three attempts by default, but there is `taker_utxo_retries` setting in `joinmarket.cfg`). And this isn't something specific to RaspiBolt.

**Comment by raindogdance** [comment]
Thank you for the quick reply! So if I understand right, those messages can be ignored safely.  

> And this isn't something specific to RaspiBolt.  

Yes, sorry, I suspected it maybe has something to do with the specific Raspibolt/JM configuration, but looks that I was wrong. Closing now.
